Added shelter and gate occupation icon and animation
henpemaz/Rain-Meadow pull request #444
Opened 2024-11-11 22:16 UTC by Zed9876

[RainmeadowShelterGateIcon (2).zip](https://github.com/user-attachments/files/17708593/RainmeadowShelterGateIcon.2.zip)

Shelters and gates will now make slugcats permanently display icons that correlate to the type of room they are in

2024-11-11 22:23 UTC, Zed9876 commented
Just realised that the video was cut short at the beggining for some reason. find a better one here.
[ShelterAndGateIcon.zip](https://github.com/user-attachments/files/17708649/ShelterAndGateIcon.zip)

2024-11-12 01:00 UTC, youbitchoc requested changes
logic lgtm but pls make it more elegant

2024-11-12 01:47 UTC, youbitchoc commented
just watched the vid and i think the offset flashing looks weird

2024-11-12 01:55 UTC, youbitchoc commented
yeah if everything flashes together we could simplify the code

2024-11-12 06:20 UTC, Zed9876 commented on Story/OnlineUIComponents/OnlinePlayerDisplay.cs
> +                }
Not sure, it was in the code before I touched it, i moved it to where it currently is, but I'll try removing it and see what happens.

2024-11-12 06:24 UTC, Zed9876 commented
Awesome, I'll get on the changes asap! (＾＾)ｂ

2024-11-12 22:25 UTC, youbitchoc commented on Story/OnlineUIComponents/OnlinePlayerDisplay.cs
> +                    else if (!this.flippedColor)
this if part is redundant, also consider flipping colour outside with foo = !foo

2024-11-12 22:27 UTC, youbitchoc commented on Story/OnlineUIComponents/OnlinePlayerDisplay.cs
> +                    else if (!this.flippedColor)
see snippet at https://github.com/henpemaz/Rain-Meadow/pull/444#discussion_r1837347544

2024-11-16 12:07 UTC, Zed9876 commented
I have found a few bugs during some more testing I've done today, will try and patch them asap.
Bugs found:
- Host Icon not showing (fixed)
- chat text showing above players' heads permanently


Will update as I progress

2024-11-19 21:50 UTC, 6fears7 approved these changes

2024-11-19 21:50 UTC, merged