only let host add to room
henpemaz/Rain-Meadow pull request #542
Opened 2024-12-10 21:21 UTC by 6fears7

- [ ]  Needs testing

2024-12-10 23:59 UTC, 6fears7 commented
VoidSpawn infinite null reffs on BodyChunks when present:

[Client]

```
[Error  :RainMeadow] 23:33:08|68999|OnlineResource.State.ReadTo:Failed to read state to entity in Room SHSH_B10 : VoidSpawn #2697:apo:0001 from local:8720
[Error  :RainMeadow] 23:33:08|68999|OnlineResource.State.ReadTo:System.IndexOutOfRangeException: Index was outside the bounds of the array.
  at RainMeadow.RealizedPhysicalObjectState.ReadTo (RainMeadow.OnlineEntity onlineEntity) [0x00039] in C:\Users\6fear\source\repos\Rain-Meadow\Online\State\RealizedPhysicalObjectState.cs:32
```


### Relevant code:

https://github.com/henpemaz/Rain-Meadow/blob/main/Online/State/RealizedPhysicalObjectState.cs#L32


Issue is an out-of-range index error every packet that clogs network. VoidSpawns specifically have differing length of their bodyChunks compared to their chunkState, so I added a equivalency check to ensure the index mismatch doesn't happen. 

### Replicate Error
1. Go to Moon and get hasGlow
2. Go to SH_S07 or any room with VoidSpawns present, really. 
3. Observe client logs

Please send thoughts.

2024-12-11 00:06 UTC, 6fears7 commented
this will result in a "desync" of sorts with the void spawns. local player won't have what remote player has, but neither would overlap either.

2024-12-11 00:13 UTC, youbitchoc commented
```cs
public void GenerateBody()
{
	int num = Random.Range(3, Random.Range(3, 16));
	for (int i = 0; i < num; i++)
	{
		val.Add(new BodyChunk(this, num2, default(Vector2), num7, num7 * 0.1f));
	}
	base.bodyChunks = val.ToArray();
}
```

random state isn't synced so they can have different body lengths

can we just not sync the void spawn? add them to the shouldsyncapoin(room|world) blocklist

2024-12-11 00:16 UTC, 6fears7 commented
Oh sweet easy enough

2024-12-11 00:20 UTC, youbitchoc requested changes
imo we simply shouldn't sync voidspawn

2024-12-11 00:20 UTC, youbitchoc commented on Story/StoryHooks.cs
> +            if (isStoryMode(out var _) && !OnlineManager.lobby.isOwner)
feels a bit silly to only allow host to spawn them

also this desynced bodychunk issue _will_ affect other gamemodes too so it doesn't make sense to gate it behind story

2024-12-11 00:20 UTC, youbitchoc commented on Online/State/RealizedPhysicalObjectState.cs
> +            if (!opo.lenientPos && chunkStates != null)
why do we need a nullcheck?

2024-12-11 00:20 UTC, youbitchoc commented on Online/State/RealizedPhysicalObjectState.cs
> +                    if (po.bodyChunks.Length == chunkStates.Length)
do we *have* to check this every loop?

2024-12-11 02:48 UTC, 6fears7 commented
I agree I'll update PR tomorrow

2024-12-11 20:28 UTC, closed without merging