removed death messages from void sea scene
henpemaz/Rain-Meadow pull request #614
Opened 2024-12-26 19:08 UTC by Zed9876

Death messages no longer show when inside the void sea as not to ruin emersion.

2024-12-26 19:19 UTC, 6fears7 submitted a review, later dismissed

2024-12-26 23:20 UTC, henpemaz commented
never resets to false?

2024-12-26 23:53 UTC, Zed9876 commented
I'll double-check with some more testing.

2024-12-27 14:13 UTC, 6fears7 requested changes

2024-12-27 14:13 UTC, 6fears7 commented on Story/StoryHooks.cs
> +            inVoidSea = false;
Set this inside the story mode game mode check please

2024-12-28 13:17 UTC, 6fears7 approved these changes

2024-12-28 13:17 UTC, merged